### ISSUE TITLE
alternate URLs for APS CATs

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apsbss#10]
Add to the documentation that APS CATs might need to use either `catdtn01` or `catdtn02`, rather than `xraydtn01` in the `DM_APS_DB_WEB_SERVICE_URL`: https://github.com/BCDA-APS/apsbss/blob/440c1039f5b392167f4e66746f23a0937f05791e/apsbss/apsbss.py#L77

- @newville, Thanks for trying this out!
- @sveseli, Thanks for the tip!

**Comment by prjemian** [comment]
@sveseli - Is this still the situation?

**Comment by sveseli** [comment]
Yes.

**Comment by prjemian** [comment]
Are they identical? Is there a reason to pick one versus the other?

**Comment by sveseli** [comment]
Functionally, they are identical. We've been using convention "odd sector=>catdtn01; even sector =>catdtn02" to split beamlines between them.

**Comment by prjemian** [comment]
Thanks.  Will implement with check for shell environment variable and fallback to some default.

**Comment by prjemian** [comment]
```py
def _get_web_service_url():
    """CATs get a different server than XSD."""
    url = os.environ.get("DM_APS_DB_WEB_SERVICE_URL")
    if url is None:
        if is_aps_workstation():
            url = "https://xraydtn01.xray.aps.anl.gov:11236"
        else:
            server = random.randint(1, 2)  # 1 or 2
            url = f"https://xraydtn{server:02.0f}.xray.aps.anl.gov:11236"
    return url
```

**Comment by sveseli** [comment]
Personally, I do not like hardcoding port numbers and machines like that. I would simply throw some sort of configuration error if the variable is not defined.

**Comment by prjemian** [comment]
Simpler?

```py
def _get_web_service_url():
    """CATs get a different server than XSD."""
    xsd_url = "https://xraydtn01.xray.aps.anl.gov:11236"
    url = os.environ.get("DM_APS_DB_WEB_SERVICE_URL", xsd_url)
    return url
```

**Comment by prjemian** [comment]
There's no config file.  Hardly worth it just for this one env var.  Want it to still work out of the box for XSD beamlines.

**Comment by sveseli** [comment]
Just so you are aware, 11236 port is not guaranteed to stay the same, and neither is the machine on which the service runs.

**Comment by newville** [comment]
@prjemian @sveseli Thanks for this... I will try this out!
