### ISSUE TITLE
Add PV's for start/end times as timestamps

### ISSUE THREAD

**Issue by canismarko** [BCDA-APS/apsbss#12]
Currently, the following PVs are available on the local BSS module as strings:

- Proposal start (${P}:proposal:startDate)
- Proposal end (${P}:proposal:endDate)
- ESAF start (${P}:esaf:startDate)
- ESAF end (${P}:esaf:endDate)

If possible, could there also be PVs with these values as numbers given the unix-epoch timestamp? Not sure if integers or floats is better, probably depends on how much precision the source data has?

Two use cases come to mind:

1) Compatibility with the pydm date time widget, which expects numbers.
2) These signals could then be included in the ophyd BSS device and used to do math for how old the proposal/ESAF are.

Use case 2 is not that tricky to work around by converting the string to a timestamp, but use case 1 requires a custom widget or a regular QDateTime widget with the logic in python.

**Comment by prjemian** [comment]
Integers would be the appropriate choice; not recording to fractional seconds.  At this time, these dates are now represented internally as Python `datetime.datetime` objects.  It's easy to write `round(dt_object.timestamp())` to integer PVs
