### ISSUE TITLE
update continuous integration scripting

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apsbss#19]

**Comment by prjemian** [comment]
Unit testing will continue to be a problem since APS systems are expected.
This code is not expected to be run outside of APS.

**Comment by prjemian** [comment]
CI failed to import dm, need to add `apsu` channel for that package.

**Comment by prjemian** [comment]
Unit tests end in CI with segmentation fault at these two lines:
https://github.com/BCDA-APS/apsbss/blob/5129f05eec6233f2437bc6271cbc51b488b7cccc/apsbss/tests/test_apsbss.py#L187
https://github.com/BCDA-APS/apsbss/blob/5129f05eec6233f2437bc6271cbc51b488b7cccc/apsbss/apsbss.py#L119

It fails from the CA layer below PyEpics.  Wonder if switching the command layer to caproto would help?

```py
ophyd.set_cl("caproto")
```

**Comment by prjemian** [comment]
All CI passes now.  So, caproto to the rescue here.  (@tacaswell would be so proud if he only knew!)

**Comment by tacaswell** [comment]
What was failing for libca that worked with caproto?  That almost sounds like a bug in caproto to me!

**Comment by tacaswell** [comment]
Ah, a segfault.  Would have to track down where you were getting libca from.
